version: '3.8'

services:
  pennypincherdb:
    image: daimyo0/pennypincherdb:1.0
    container_name: pennypincherdb
    ports:
      - "3306:3306"
    networks:
      - pennypincher-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  pennypincherapp:
    image: daimyo0/pennypincherapp:1.0
    container_name: pennypincherapp
    depends_on:
      pennypincherdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pennypincherdb:3306/PennyPincher
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - pennypincher-network

networks:
  pennypincher-network:
    driver: bridge
